run:
  concurrency: 4
  timeout: 5m
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - godox
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - testableexamples
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - zerologlint
    - canonicalheader
    - copyloopvar
    - fatcontext
    - gochecksumtype
    - perfsprint
    - sloglint
    - spancheck
    - testifylint
